# Generated by Django 5.0 on 2024-12-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('business_name', models.CharField(help_text='Nombre legal de la empresa proveedora', max_length=200, verbose_name='Razón Social')),
                ('commercial_name', models.CharField(blank=True, help_text='Nombre comercial o de fantasía del proveedor', max_length=200, verbose_name='Nombre Comercial')),
                ('tax_id', models.CharField(help_text='Número de identificación fiscal (DNI, CUIT, CUIL, etc.)', max_length=20, unique=True, verbose_name='Identificación Fiscal')),
                ('contact_person', models.CharField(help_text='Nombre completo de la persona de contacto principal', max_length=100, verbose_name='Persona de Contacto')),
                ('email', models.EmailField(help_text='Correo electrónico principal del proveedor', max_length=254, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(help_text='Número de teléfono principal del proveedor', max_length=20, verbose_name='Teléfono')),
                ('address', models.TextField(help_text='Dirección completa del proveedor', verbose_name='Dirección')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('country', models.CharField(max_length=100, verbose_name='País')),
                ('bank_name', models.CharField(blank=True, help_text='Nombre del banco para transferencias', max_length=100, verbose_name='Banco')),
                ('bank_cbu_alias', models.CharField(blank=True, help_text='CBU o ALIAS bancario para transferencias', max_length=100, verbose_name='CBU/ALIAS')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el proveedor está activo en el sistema', verbose_name='Activo')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre el proveedor', verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['business_name'],
                'indexes': [models.Index(fields=['business_name'], name='suppliers_s_busines_a00fdc_idx'), models.Index(fields=['tax_id'], name='suppliers_s_tax_id_b5d5af_idx')],
            },
        ),
    ]
