# Generated by Django 5.0 on 2024-12-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('date', models.DateField(help_text='Fecha en que se realizó el gasto', verbose_name='Fecha del gasto')),
                ('expense_type', models.CharField(choices=[('SAL', 'Salarios'), ('UTL', 'Servicios'), ('MKT', 'Marketing'), ('SHI', 'Envíos'), ('TAX', 'Impuestos'), ('PLT', 'Plataforma'), ('SUP', 'Insumos'), ('LOG', 'Logística'), ('OTH', 'Otros')], default='OTH', help_text='Categoría o tipo de gasto realizado', max_length=3, verbose_name='Tipo de gasto')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto total del gasto', max_digits=10, verbose_name='Monto')),
                ('observations', models.TextField(blank=True, help_text='Observaciones o notas adicionales sobre el gasto', verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-date'],
            },
        ),
    ]
