# Generated by Django 5.0 on 2025-02-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='expense_type',
            field=models.CharField(choices=[('SAL', 'Salarios'), ('UTL', 'Servicios'), ('MOB', 'Movilidad'), ('MKT', 'Marketing'), ('SHI', 'Envíos'), ('TAX', 'Impuestos'), ('PLT', 'PlataformaS'), ('SUP', 'Insumos'), ('LOG', 'Logística'), ('PUB', 'Publicidad'), ('REN', 'Alquiler'), ('OTH', 'Otros')], default='OTH', help_text='Categoría o tipo de gasto realizado', max_length=3, verbose_name='Tipo de gasto'),
        ),
    ]
