# Generated by Django 5.0 on 2025-05-31 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_migrate_expense_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensetype',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='expense_type',
            field=models.ForeignKey(help_text='Categoría o tipo de gasto realizado', null=True, on_delete=django.db.models.deletion.PROTECT, to='expenses.expensetype', verbose_name='Tipo de gasto'),
        ),
    ]
