# Generated by Django 5.0 on 2025-05-31 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_expensetype_deleted_at_alter_expenses_expense_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='is_fixed',
            field=models.BooleanField(help_text='Indica si el gasto es fijo o variable', null=True, verbose_name='Gasto fijo'),
        ),
    ]
